ruler_storage:
  backend: filesystem
  local:
    directory: /tmp/mimir/rules

ruler:
  enable_api: true
  poll_interval: 1s

alertmanager_storage:
  backend: filesystem
  local:
    path: /tmp/mimir/alerts