package grafana

import (
	"fmt"
	"path/filepath"

	"github.com/grafana/grizzly/pkg/grizzly"
	"github.com/grafana/tanka/pkg/kubernetes/manifest"
)

/*
 * @TODO
 * 1. The API does not have a GET method, so we have to fake it here
 * 2. The API expects an ID and a tenantId in an update, but these are
 *    generated by the server so cannot be represented in Jsonnet.
 *    Therefore, we have to pre-retrieve the check to get those values
 *    so we can inject them before posting JSON.
 * 3. This means pre-retrieving the check *twice*, once to establish
 *    whether this resource has changed or not (within Grizzly ifself)
 *    and again within this provider to retrieve IDs. Not ideal.
 */

// SyntheticMonitoringHandler is a Grizzly Handler for Grafana Synthetic Monitoring
type SyntheticMonitoringHandler struct {
	Provider Provider
}

// NewSyntheticMonitoringHandler returns a Grizzly Handler for Grafana Synthetic Monitoring
func NewSyntheticMonitoringHandler(provider Provider) *SyntheticMonitoringHandler {
	return &SyntheticMonitoringHandler{
		Provider: provider,
	}
}

// Kind returns the name for this handler
func (h *SyntheticMonitoringHandler) Kind() string {
	return "SyntheticMonitoringCheck"
}

// APIVersion returns the group and version for the provider of which this handler is a part
func (h *SyntheticMonitoringHandler) APIVersion() string {
	return h.Provider.APIVersion()
}

// GetExtension returns the file name extension for a check
func (h *SyntheticMonitoringHandler) GetExtension() string {
	return "json"
}

const (
	syntheticMonitoringCheckGlob = "synthetic-monitoring/check-*"
	syntheticMonitoringPattern   = "synthetic-monitoring/check-%s.%s"
)

// FindResourceFiles identifies files within a directory that this handler can process
func (h *SyntheticMonitoringHandler) FindResourceFiles(dir string) ([]string, error) {
	path := filepath.Join(dir, syntheticMonitoringCheckGlob)
	return filepath.Glob(path)
}

// Validate returns the uid of resource
func (h *SyntheticMonitoringHandler) Validate(resource grizzly.Resource) error {
	job, exist := resource.GetSpecString("job")
	if exist {
		if job != resource.Name() {
			return fmt.Errorf("job '%s' and name '%s', don't match", job, resource.Name())
		}
	}
	settings := resource.GetSpecValue("settings").(map[string]interface{})
	if _, ok := settings[resource.GetMetadata("type")]; !ok {
		return fmt.Errorf("type '%s' is incorrect", resource.GetMetadata("type"))
	}
	return nil
}

// ResourceFilePath returns the location on disk where a resource should be updated
func (h *SyntheticMonitoringHandler) ResourceFilePath(resource grizzly.Resource, filetype string) string {
	return fmt.Sprintf(syntheticMonitoringPattern, resource.Name(), filetype)
}

// Parse parses a manifest object into a struct for this resource type
func (h *SyntheticMonitoringHandler) Parse(m manifest.Manifest) (grizzly.Resources, error) {
	resource := grizzly.Resource(m)
	resource.SetSpecString("job", resource.GetMetadata("name"))
	return grizzly.Resources{resource}, nil
}

// Unprepare removes unnecessary elements from a remote resource ready for presentation/comparison
func (h *SyntheticMonitoringHandler) Unprepare(resource grizzly.Resource) *grizzly.Resource {
	resource.DeleteSpecKey("tenantId")
	resource.DeleteSpecKey("id")
	resource.DeleteSpecKey("modified")
	resource.DeleteSpecKey("created")
	return &resource
}

// Prepare gets a resource ready for dispatch to the remote endpoint
func (h *SyntheticMonitoringHandler) Prepare(existing, resource grizzly.Resource) *grizzly.Resource {
	resource.SetSpecValue("tenantId", existing.GetSpecValue("tenantId"))
	resource.SetSpecValue("id", existing.GetSpecValue("id"))
	return &resource
}

// GetUID returns the UID for a resource
func (h *SyntheticMonitoringHandler) GetUID(resource grizzly.Resource) (string, error) {
	if !resource.HasMetadata("type") {
		return "", fmt.Errorf("%s %s lacks a type metadata element", h.Kind(), resource.Name())
	}
	return fmt.Sprintf("%s.%s", resource.GetMetadata("type"), resource.Name()), nil
}

// GetByUID retrieves JSON for a resource from an endpoint, by UID
func (h *SyntheticMonitoringHandler) GetByUID(UID string) (*grizzly.Resource, error) {
	return getRemoteCheck(UID)
}

// GetRemote retrieves a datasource as a Resource
func (h *SyntheticMonitoringHandler) GetRemote(resource grizzly.Resource) (*grizzly.Resource, error) {
	uid := fmt.Sprintf("%s.%s", resource.GetMetadata("type"), resource.Name())
	return getRemoteCheck(uid)
}

// ListRemote retrieves as list of UIDs of all remote resources
func (h *SyntheticMonitoringHandler) ListRemote() ([]string, error) {
	return getRemoteCheckList()
}

// Add adds a new check to the SyntheticMonitoring endpoint
func (h *SyntheticMonitoringHandler) Add(resource grizzly.Resource) error {
	return addCheck(resource)
}

// Update pushes an updated check to the SyntheticMonitoring endpoing
func (h *SyntheticMonitoringHandler) Update(existing, resource grizzly.Resource) error {
	return updateCheck(resource)
}
