name: Feature Request
description: Suggest an improvement for Grizzly
title: "[Feature Request]: "
labels: ["enhancement", "triage"]
projects: ["grafana/513"] # Platform Client Administration Tooling
body:
  - type: textarea
    id: request
    attributes:
      label: Feature Request
      placeholder: |
        What would you like to see added/changed to Grizzly?
