---
kind: pipeline
name: check
services:
- commands:
  - apk add docker make && make run-test-image
  image: alpine
  name: grizzly-grafana
  ports:
  - 3001
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
steps:
- commands:
  - go mod download
  image: golang:1.20.6
  name: download
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- commands:
  - make lint
  depends_on:
  - download
  image: golang:1.20.6
  name: lint
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- commands:
  - go test ./cmd/... ./pkg/...
  image: golang:1.20.6
  name: test
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- commands:
  - make dev
  depends_on:
  - download
  image: golang:1.20.6
  name: dev
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- commands:
  - go test -v ./integration/...
  depends_on:
  - dev
  image: golang:1.20.6
  name: integration
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
- name: gopath
  temp: {}
---
kind: pipeline
name: release
steps:
- commands:
  - git fetch origin --tags
  image: golang:1.20.6
  name: fetch-tags
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- commands:
  - make cross
  image: golang:1.20.6
  name: cross
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- image: plugins/github-release
  name: publish
  settings:
    api_key:
      from_secret: github_token
    draft: true
    files: dist/*
    note: |
      This is release ${DRONE_TAG} of Grizzly (`grr`). Check out the [CHANGELOG](CHANGELOG.md) for detailed release notes.
      ## Install instructions

      #### Binary:
      ```bash
      # download the binary (adapt os and arch as needed)
      $ curl -fSL -o "/usr/local/bin/grr" "https://github.com/grafana/grizzly/releases/download/${DRONE_TAG}/grr-linux-amd64"

      # make it executable
      $ chmod a+x "/usr/local/bin/grr"

      # have fun :)
      $ grr --help
      ```
    title: ${DRONE_TAG}
trigger:
  event:
  - tag
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
- name: gopath
  temp: {}
---
kind: pipeline
name: docker-amd64
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - make static
  image: golang:1.20.6
  name: static
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- image: plugins/docker
  name: container
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    password:
      from_secret: docker_password
    repo: grafana/grizzly
    username:
      from_secret: docker_username
trigger:
  ref:
  - refs/heads/main
  - refs/heads/docker
  - refs/tags/v*
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
- name: gopath
  temp: {}
---
kind: pipeline
name: docker-arm64
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - make static
  image: golang:1.20.6
  name: static
  volumes:
  - name: gopath
    path: /go
  - name: docker
    path: /var/run/docker.sock
- image: plugins/docker
  name: container
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    password:
      from_secret: docker_password
    repo: grafana/grizzly
    username:
      from_secret: docker_username
trigger:
  ref:
  - refs/heads/main
  - refs/heads/docker
  - refs/tags/v*
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
- name: gopath
  temp: {}
---
depends_on:
- docker-amd64
- docker-arm64
kind: pipeline
name: manifest
steps:
- image: plugins/manifest
  name: manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: .drone/docker-manifest.tmpl
    username:
      from_secret: docker_username
trigger:
  ref:
  - refs/heads/main
  - refs/heads/docker
  - refs/tags/v*
type: docker
volumes:
- host:
    path: /var/run/docker.sock
  name: docker
- name: gopath
  temp: {}
---
get:
  name: pat
  path: infra/data/ci/github/grafanabot
kind: secret
name: github_token
---
get:
  name: username
  path: infra/data/ci/docker_hub
kind: secret
name: docker_username
---
get:
  name: password
  path: infra/data/ci/docker_hub
kind: secret
name: docker_password
---
kind: signature
hmac: 0a221e4c3cc521c5240af425993362b6643af13016dc131eb36752fdfb1864a4

...
